In [1]:
import ikamoana.fisheries_effort.fisheries_effort as fe
import numpy as np

In [2]:
filepath = "./data/fisheries_effort/fisheries_data_2021_Nov8.txt"

In [3]:
fisheries_df = fe.readFile(filepath, header_position=0, columns_name=None)
fisheries_dict = fe.separateFisheries(fisheries_df)
fisheries_rescaled_dict = fe.rescaleFisheries({15:fisheries_dict[15]})
fisheries_groub_by_dict = fe.groupByFisheries(fisheries_rescaled_dict)
fisheries_effort_ds, fisheries_catch_ds = fe.fisheriesToDataSet(fisheries_groub_by_dict)
fisheries_effort_ds

<xarray.Dataset>
Dimensions:  (time: 356, lat: 50, lon: 54)
Coordinates:
  * time     (time) datetime64[ns] 1974-01-15 1974-03-15 ... 2014-08-15
  * lat      (lat) float64 -17.5 -16.5 -15.5 -14.5 -13.5 ... 29.5 30.5 31.5 32.5
  * lon      (lon) float64 212.5 213.5 214.5 215.5 ... 262.5 264.5 265.5 266.5
Data variables:
    15       (time, lat, lon) float64 nan nan nan nan nan ... nan nan nan nan
Attributes:
    Type:     E

In [4]:
effort_sum = fe.sumDataSet(fisheries_effort_ds)
effort_sum

<xarray.DataArray (time: 356, lat: 50, lon: 54)>
array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
...
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]])
Coordinates:
  * time     (time) datetime64[ns] 1974-01-15 1974-03-15 ... 2014-08-15
  * lat      (lat) float64 -17.5 -16.5 -15.5 -14.5 -13.5 ... 29.5 30.5 31.5 32.5
  * lon      (lon) float64 212.5 213.5 214.5 215.5 ... 262.5 264.5 265.5 266.5
Attributes:
    Type:     Sum of E

In [5]:
print("Original : ",float(fisheries_effort_ds[15].sum()))
print("Sum      : ",float(effort_sum.sum()))

Original :  48865.0
Sum      :  48865.0


> ### Verification of the coords size (continuous ?)

In [6]:
lat_o = effort_sum.lat.data
lat_s = np.arange(effort_sum.lat.data[0],effort_sum.lat.data[-1]+0.001, step=1.0)
print((lat_o.size == lat_s.size)," : ",lat_o.size," | ",lat_s.size)
#np.sum(lat_o == lat_s) == lat_s.size == lat_o.size

False  :  50  |  51


In [7]:
lon_o = effort_sum.lon.data
lon_s = np.arange(effort_sum.lon.data[0],effort_sum.lon.data[-1]+0.001, step=1.0)
print((lon_o.size == lon_s.size)," : ",lon_o.size," | ",lon_s.size)
#np.sum(lon_o == lon_s) == lon_s.size == lon_o.size

False  :  54  |  55


In [8]:
time_o = np.array(effort_sum.time.data,dtype='datetime64[M]')
time_s = np.arange(time_o[0],time_o[-1]+1)
print((time_o.size == time_s.size)," : ",time_o.size," | ",time_s.size)
#np.sum(time_o == time_s) == time_s.size == time_o.size

False  :  356  |  488


---
## Make the coords be continuous

In [9]:
print(time_o[0],time_o[-1])
print(time_s[0],time_s[-1])

1974-01 2014-08
1974-01 2014-08


In [13]:
#es_reindex = effort_sum.reindex(time=time_s,method='nearest')
#es_reindex = effort_sum.reindex(time=time_s,method='pad')
es_reindex = effort_sum.reindex(time=time_s)
es_reindex

<xarray.DataArray (time: 488, lat: 50, lon: 54)>
array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
...
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]])
Coordinates:
  * time     (time) datetime64[ns] 1974-01-01 1974-02-01 ... 2014-08-01
  * lat      (lat) float64 -17.5 -16.5 -15.5 -14.5 -13.5 ... 29.5 30.5 31.5 32.5
  * lon      (lon) float64 212.5 213.5 214.5 215.5 ... 262.5 264.5 265.5 266.5
Attributes:
    Type:     Sum of E

In [11]:
print(effort_sum.data.shape)
print(es_reindex.data.shape)

(356, 50, 54)
(488, 50, 54)


# **TODO :**
### Faire correspondre les dates pour ne pas perdre les données.
Problème : les résolutions ne sont pas toujours les mêmes et les fichiers n'ont pas les mêmes coordonnées.

Solution : Utiliser une réindexation avec la valeur de coordonnée la plus proche.

#### 1. Méthode
- reindex(method='nearest')
- reindex_like(method='nearest')

In [18]:
#es_reindex = effort_sum.reindex(time=time_s,method='nearest')
#es_reindex = effort_sum.reindex(time=time_s,method='pad')
es_reindex = effort_sum.reindex(time=time_s, method=None)
es_reindex

<xarray.DataArray (time: 488, lat: 50, lon: 54)>
array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
...
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]])
Coordinates:
  * time     (time) datetime64[ns] 1974-01-01 1974-02-01 ... 2014-08-01
  * lat      (lat) float64 -17.5 -16.5 -15.5 -14.5 -13.5 ... 29.5 30.5 31.5 32.5
  * lon      (lon) float64 212.5 213.5 214.5 215.5 ... 262.5 264.5 265.5 266.5
Attributes:
    Type:     Sum of E

In [19]:
print("effort_sum : ",float(np.nansum(effort_sum.data)))
print("es_reindex : ",float(np.nansum(es_reindex.data)))

effort_sum :  48865.0
es_reindex :  0.0


#### 2. Autre méthode :

- Index Forçage.
- Index Effort.
- Attribuer à chaque coordonnée dans index effort sa position dans l'index forçage (Nearest).
- Créer un numpy ndarray (zero) dans la shape de Forçage.
- Boucle FOR qui transfert d'Effort vers le nouvel array.