In [2]:
import sys
sys.path.append('./../')

In [3]:
import numpy as np
import ikamoana as ika
from ikamoana.ikamoanafields import sliceField
from ikamoana.feedinghabitat import coordsAccess

In [4]:
file = './../data/feeding_habitat_data/po_2x30_historical_interim/skj_po_interim_2deg_configuration_file.xml'
ika_gen = ika.ikamoanafields.IkamoanaFields(file,file)

# 1. Create Fields

In [24]:
field_one = ika_gen.computeEvolvingTaxis(
    cohort_start=7, cohort_end=10,
    time_start=355, time_end=358,
    lat_min=7, lat_max=52,
    lon_min=15, lon_max=100)

In [25]:
field_two = ika_gen.computeEvolvingTaxis(
    cohort_start=7,cohort_end=10,
    time_start=355,time_end=358,
    use_already_computed_habitat=False)


In [26]:
A = field_one[0]
B = field_two[0]
print("A longitude :\n",A.lon.data[0],A.lon.data[-1]) 
print("\nB longitude :\n",B.lon.data[0],B.lon.data[-1])

A longitude :
 119.5 289.5

B longitude :
 89.5 289.5


# 2. Three way to resize
### a ) Using `reindex_like()`

In [21]:
B.reindex_like(A)

<xarray.DataArray 'Taxis_longitude_Feeding_Habitat_Cohort_7_to_10' (time: 4, lat: 46, lon: 86)>
array([[[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          2.6868458e-06,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          1.6028745e-06,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         -1.5114301e-06,  0.0000000e+00,  0.0000000e+00],
        ...,
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00]],

       [[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          1.1816159e-06,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          5.7855527e-07,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         -1.4642428e-06,  0.0000000e+00,  0.0000000e+00],
...
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00]],

       [[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         -2.8982572e-06,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         -3.8493349e-06,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         -2.7892904e-06,  0.0000000e+00,  0.0000000e+00],
        ...,
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00]]], dtype=float32)
Coordinates:
  * lat      (lat) float64 50.5 48.5 46.5 44.5 42.5 ... -33.5 -35.5 -37.5 -39.5
  * time     (time) datetime64[ns] 2008-08-16T12:00:00 ... 2008-11-15T12:00:00
  * lon      (lon) float64 119.5 121.5 123.5 125.5 ... 283.5 285.5 287.5 289.5
    cohorts  (time) int64 7 8 9 10
Attributes:
    description:   Feeding habitat of a species that evolves over time.
    cohort_start:  7
    cohort_end:    10
    time_start:    355
    time_end:      358
    lat_min:       None
    lat_max:       None
    lon_min:       None
    lon_max:       None
    eF_list:       [3.999907116416026, 0.05, 0.897307278945509, 0.0, 0.0, 3.9...
    sigma_0:       1.492626509052
    sigma_K:       3.00000257690523
    T_star_1:      31.09996321152416
    T_star_K:      26.04960048814059
    bT:            2.83057972721579
    gamma:         0.0001000000005808978
    o_star:        3.764163854561827
    deltaT:        30.0
    space_reso:    2.0

### b ) Using `loc()`
> Will find the nearest values

In [23]:
B.loc[min(A.time.data):max(A.time.data),
      max(A.lat.data):min(A.lat.data),
      min(A.lon.data):max(A.lon.data)]

<xarray.DataArray 'Taxis_longitude_Feeding_Habitat_Cohort_7_to_10' (time: 4, lat: 46, lon: 86)>
array([[[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          2.6868458e-06,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          1.6028745e-06,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         -1.5114301e-06,  0.0000000e+00,  0.0000000e+00],
        ...,
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00]],

       [[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          1.1816159e-06,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          5.7855527e-07,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         -1.4642428e-06,  0.0000000e+00,  0.0000000e+00],
...
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00]],

       [[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         -2.8982572e-06,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         -3.8493349e-06,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         -2.7892904e-06,  0.0000000e+00,  0.0000000e+00],
        ...,
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00]]], dtype=float32)
Coordinates:
  * lat      (lat) float32 50.5 48.5 46.5 44.5 42.5 ... -33.5 -35.5 -37.5 -39.5
  * time     (time) datetime64[ns] 2008-08-16T12:00:00 ... 2008-11-15T12:00:00
  * lon      (lon) float32 119.5 121.5 123.5 125.5 ... 283.5 285.5 287.5 289.5
    cohorts  (time) int64 7 8 9 10
Attributes:
    description:   Feeding habitat of a species that evolves over time.
    cohort_start:  7
    cohort_end:    10
    time_start:    355
    time_end:      358
    lat_min:       None
    lat_max:       None
    lon_min:       None
    lon_max:       None
    eF_list:       [3.999907116416026, 0.05, 0.897307278945509, 0.0, 0.0, 3.9...
    sigma_0:       1.492626509052
    sigma_K:       3.00000257690523
    T_star_1:      31.09996321152416
    T_star_K:      26.04960048814059
    bT:            2.83057972721579
    gamma:         0.0001000000005808978
    o_star:        3.764163854561827
    deltaT:        30.0
    space_reso:    2.0

### c ) Using `coordsAccess()` and `sliceField()`

In [27]:
access_time, access_lat, access_lon = coordsAccess(B.coords)

minlon_idx = access_lon(min(A.lon.data))
maxlon_idx = access_lon(max(A.lon.data))
minlat_idx = access_lat(max(A.lat.data))
maxlat_idx = access_lat(min(A.lat.data))
mintime_idx = access_time(min(A.time.data))
maxtime_idx = access_time(max(A.time.data))
sliceField(B, mintime_idx,maxtime_idx, minlat_idx,maxlat_idx, minlon_idx,maxlon_idx)

<xarray.DataArray 'Taxis_longitude_Feeding_Habitat_Cohort_7_to_10' (time: 4, lat: 46, lon: 86)>
array([[[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          2.6868458e-06,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          1.6028745e-06,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         -1.5114301e-06,  0.0000000e+00,  0.0000000e+00],
        ...,
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00]],

       [[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          1.1816159e-06,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          5.7855527e-07,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         -1.4642428e-06,  0.0000000e+00,  0.0000000e+00],
...
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00]],

       [[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         -2.8982572e-06,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         -3.8493349e-06,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         -2.7892904e-06,  0.0000000e+00,  0.0000000e+00],
        ...,
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00]]], dtype=float32)
Coordinates:
  * lat      (lat) float32 50.5 48.5 46.5 44.5 42.5 ... -33.5 -35.5 -37.5 -39.5
  * time     (time) datetime64[ns] 2008-08-16T12:00:00 ... 2008-11-15T12:00:00
  * lon      (lon) float32 119.5 121.5 123.5 125.5 ... 283.5 285.5 287.5 289.5
    cohorts  (time) int64 7 8 9 10
Attributes:
    description:   Feeding habitat of a species that evolves over time.
    cohort_start:  7
    cohort_end:    10
    time_start:    355
    time_end:      358
    lat_min:       None
    lat_max:       None
    lon_min:       None
    lon_max:       None
    eF_list:       [3.999907116416026, 0.05, 0.897307278945509, 0.0, 0.0, 3.9...
    sigma_0:       1.492626509052
    sigma_K:       3.00000257690523
    T_star_1:      31.09996321152416
    T_star_K:      26.04960048814059
    bT:            2.83057972721579
    gamma:         0.0001000000005808978
    o_star:        3.764163854561827
    deltaT:        30.0
    space_reso:    2.0