In [1]:
import sys
sys.path.append('./../')

In [2]:
import numpy as np
import ikamoana as ika

In [4]:
file = ('/home/ash/Documents/GitHub_Repositories/OFP-Ikamoana/Ikamoana/data/'
        'feeding_habitat_data/po_2x30_historical_interim/skj_po_interim_2deg_configuration_file.xml')
ika_gen = ika.ikamoanafields.IkamoanaFields(file)

---
# Taxis

In [5]:
tlon, tlat = ika_gen.computeTaxis(
    cohort=7,
    time_start=355,
    time_end=358,
    lon_min=15,
    lon_max=100,
    lat_min=7,
    lat_max=52)
tlon

<xarray.DataArray 'Taxis_longitude_Feeding_Habitat_Cohort_7' (time: 4, lat: 46, lon: 86)>
array([[[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          1.6028745e-06,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         -1.5114301e-06,  0.0000000e+00,  0.0000000e+00],
        ...,
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00]],

       [[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          5.2222686e-07,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         -1.3216834e-06,  0.0000000e+00,  0.0000000e+00],
...
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00]],

       [[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         -2.9653177e-06,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         -2.1487172e-06,  0.0000000e+00,  0.0000000e+00],
        ...,
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00]]], dtype=float32)
Coordinates:
  * lat      (lat) float32 50.5 48.5 46.5 44.5 42.5 ... -33.5 -35.5 -37.5 -39.5
  * lon      (lon) float32 119.5 121.5 123.5 125.5 ... 283.5 285.5 287.5 289.5
  * time     (time) datetime64[ns] 2008-08-16T12:00:00 ... 2008-11-15T12:00:00
Attributes:
    Cohort number:     7
    Age start (days):  210.0
    Age end (days):    240.0
    Length (cm):       30.72
    Weight (kg):       0.53
    time_start:        355
    time_end:          358
    lat_min:           7
    lat_max:           52
    lon_min:           15
    lon_max:           100
    eF_list:           [3.999907116416026, 0.05, 0.897307278945509, 0.0, 0.0,...
    sigma_0:           1.492626509052
    sigma_K:           3.00000257690523
    T_star_1:          31.09996321152416
    T_star_K:          26.04960048814059
    bT:                2.83057972721579
    gamma:             0.0001000000005808978
    o_star:            3.764163854561827
    deltaT:            30.0
    space_reso:        2.0

In [6]:
tlat

<xarray.DataArray 'Taxis_latitude_Feeding_Habitat_Cohort_7' (time: 4, lat: 46, lon: 86)>
array([[[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        ...,
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         -2.2936551e-06,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         -3.4335185e-06,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         -2.7223614e-06,  0.0000000e+00,  0.0000000e+00]],

       [[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
...
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         -9.1699781e-07,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         -2.4097310e-06,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         -2.5877134e-06,  0.0000000e+00,  0.0000000e+00]],

       [[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        ...,
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         -9.4949894e-07,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         -2.3176442e-06,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         -2.8817719e-06,  0.0000000e+00,  0.0000000e+00]]], dtype=float32)
Coordinates:
  * lat      (lat) float32 50.5 48.5 46.5 44.5 42.5 ... -33.5 -35.5 -37.5 -39.5
  * lon      (lon) float32 119.5 121.5 123.5 125.5 ... 283.5 285.5 287.5 289.5
  * time     (time) datetime64[ns] 2008-08-16T12:00:00 ... 2008-11-15T12:00:00
Attributes:
    Cohort number:     7
    Age start (days):  210.0
    Age end (days):    240.0
    Length (cm):       30.72
    Weight (kg):       0.53
    time_start:        355
    time_end:          358
    lat_min:           7
    lat_max:           52
    lon_min:           15
    lon_max:           100
    eF_list:           [3.999907116416026, 0.05, 0.897307278945509, 0.0, 0.0,...
    sigma_0:           1.492626509052
    sigma_K:           3.00000257690523
    T_star_1:          31.09996321152416
    T_star_K:          26.04960048814059
    bT:                2.83057972721579
    gamma:             0.0001000000005808978
    o_star:            3.764163854561827
    deltaT:            30.0
    space_reso:        2.0

In [7]:
ika_gen.landmask(ika_gen.feeding_habitat)

<xarray.DataArray 'landmask' (lat: 46, lon: 86)>
array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 0., 1., 1.],
       [1., 1., 1., ..., 0., 1., 1.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)
Coordinates:
  * lat      (lat) float32 50.5 48.5 46.5 44.5 42.5 ... -33.5 -35.5 -37.5 -39.5
  * lon      (lon) float32 119.5 121.5 123.5 125.5 ... 283.5 285.5 287.5 289.5

---
# Evolving Taxis

In [8]:
etlon, etlat = ika_gen.computeEvolvingTaxis(
    cohort_start=7,
    cohort_end=10,
    time_start=355,
    time_end=358,
    lon_min=15,
    lon_max=100,
    lat_min=7,
    lat_max=52)
etlon

<xarray.DataArray 'Taxis_longitude_Feeding_Habitat_Cohort_7_to_10' (time: 4, lat: 46, lon: 86)>
array([[[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          1.6028745e-06,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         -1.5114301e-06,  0.0000000e+00,  0.0000000e+00],
        ...,
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00]],

       [[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          5.7855527e-07,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         -1.4642428e-06,  0.0000000e+00,  0.0000000e+00],
...
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00]],

       [[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         -3.8493349e-06,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         -2.7892904e-06,  0.0000000e+00,  0.0000000e+00],
        ...,
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00]]], dtype=float32)
Coordinates:
  * lat      (lat) float32 50.5 48.5 46.5 44.5 42.5 ... -33.5 -35.5 -37.5 -39.5
  * time     (time) datetime64[ns] 2008-08-16T12:00:00 ... 2008-11-15T12:00:00
  * lon      (lon) float32 119.5 121.5 123.5 125.5 ... 283.5 285.5 287.5 289.5
    cohorts  (time) int64 7 8 9 10
Attributes:
    description:   Feeding habitat of a species that evolves over time.
    cohort_start:  7
    cohort_end:    10
    time_start:    355
    time_end:      358
    lat_min:       7
    lat_max:       52
    lon_min:       15
    lon_max:       100
    eF_list:       [3.999907116416026, 0.05, 0.897307278945509, 0.0, 0.0, 3.9...
    sigma_0:       1.492626509052
    sigma_K:       3.00000257690523
    T_star_1:      31.09996321152416
    T_star_K:      26.04960048814059
    bT:            2.83057972721579
    gamma:         0.0001000000005808978
    o_star:        3.764163854561827
    deltaT:        30.0
    space_reso:    2.0

In [9]:
etlat

<xarray.DataArray 'Taxis_latitude_Feeding_Habitat_Cohort_7_to_10' (time: 4, lat: 46, lon: 86)>
array([[[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        ...,
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         -2.2936551e-06,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         -3.4335185e-06,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         -2.7223614e-06,  0.0000000e+00,  0.0000000e+00]],

       [[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
...
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         -1.1069445e-06,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         -2.9088819e-06,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         -3.1237316e-06,  0.0000000e+00,  0.0000000e+00]],

       [[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
        ...,
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         -1.2325626e-06,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         -3.0085778e-06,  0.0000000e+00,  0.0000000e+00],
        [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         -3.7408827e-06,  0.0000000e+00,  0.0000000e+00]]], dtype=float32)
Coordinates:
  * lat      (lat) float32 50.5 48.5 46.5 44.5 42.5 ... -33.5 -35.5 -37.5 -39.5
  * time     (time) datetime64[ns] 2008-08-16T12:00:00 ... 2008-11-15T12:00:00
  * lon      (lon) float32 119.5 121.5 123.5 125.5 ... 283.5 285.5 287.5 289.5
    cohorts  (time) int64 7 8 9 10
Attributes:
    description:   Feeding habitat of a species that evolves over time.
    cohort_start:  7
    cohort_end:    10
    time_start:    355
    time_end:      358
    lat_min:       7
    lat_max:       52
    lon_min:       15
    lon_max:       100
    eF_list:       [3.999907116416026, 0.05, 0.897307278945509, 0.0, 0.0, 3.9...
    sigma_0:       1.492626509052
    sigma_K:       3.00000257690523
    T_star_1:      31.09996321152416
    T_star_K:      26.04960048814059
    bT:            2.83057972721579
    gamma:         0.0001000000005808978
    o_star:        3.764163854561827
    deltaT:        30.0
    space_reso:    2.0

In [10]:
ika_gen.landmask(ika_gen.feeding_habitat)

<xarray.DataArray 'landmask' (lat: 46, lon: 86)>
array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 0., 1., 1.],
       [1., 1., 1., ..., 0., 1., 1.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)
Coordinates:
  * lat      (lat) float32 50.5 48.5 46.5 44.5 42.5 ... -33.5 -35.5 -37.5 -39.5
  * lon      (lon) float32 119.5 121.5 123.5 125.5 ... 283.5 285.5 287.5 289.5

---
# Landmask

In [12]:
ika_gen.landmask(use_SEAPODYM_global_mask=True)

<xarray.DataArray 'landmask' (lat: 60, lon: 101)>
array([[0, 0, 0, ..., 0, 0, 0],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int8)
Coordinates:
  * lat      (lat) float32 64.5 62.5 60.5 58.5 56.5 ... -47.5 -49.5 -51.5 -53.5
  * lon      (lon) float32 89.5 91.5 93.5 95.5 97.5 ... 283.5 285.5 287.5 289.5