In [1]:
import sys
sys.path.append('./../')

import ikamoana.fisherieseffort.fisherieseffort as fe
from ikamoana.ikamoanafields import (
    ikamoanafields,
    fieldsdatastructure
)
from ikamoana.feedinghabitat import (
    feedinghabitat,
    feedinghabitatconfigreader
)
import xarray as xr
import numpy as np


#xml_filepath="./../data/SEAPODYM_data/run-test/skj_interim_CL_2018_testopt.xml"
SEAPODYM_filepath = "./../data/SEAPODYM_data/run-test/skj_CLT_e5_3_est.xml"
IKAMOANA_filepath = "./IkaSim_DensityTest.xml"
fisheries_xml_filepath="./../data/SEAPODYM_data/run-test/data/fisheries/skj_fisheries_data_2021_Nov17.txt"

In [2]:
import xml.etree.ElementTree as ET
tree = ET.parse(IKAMOANA_filepath)
root = tree.getroot()
fieldsdatastructure.tagReading(
    root,
    ['forcing', 'shallow_sea_to_ocean'],
    'False'
)

0
forcing

    
1
shallow_sea_to_ocean
-1


AttributeError: 'int' object has no attribute 'text'

## Initialize

In [2]:
fh = feedinghabitat.FeedingHabitat(SEAPODYM_filepath)
ikaf = ikamoanafields.IkamoanaFields(
   IKAMOANA_filepath, SEAPODYM_filepath,
   feeding_habitat=fh.computeFeedingHabitat(0)['Feeding_Habitat_Cohort_0'])
# ikaf = ikamoanafields.IkamoanaFields(IKAMOANA_filepath, SEAPODYM_filepath)
ikaf.feeding_habitat_structure.data_structure.normalizeCoords()

In [3]:
Tx, Ty = ikaf.computeTaxis(0)

---


In [ ]:
current_u = feedinghabitat.fhcr.seapodymFieldConstructor(
    './../data/SEAPODYM_data/run-test/data/run-interim_2x30d_po/po_interim_historic_2x30d_u_L1_1979_2010.dym')
current_v = feedinghabitat.fhcr.seapodymFieldConstructor(
    './../data/SEAPODYM_data/run-test/data/run-interim_2x30d_po/po_interim_historic_2x30d_v_L1_1979_2010.dym')
habitat = fh.computeFeedingHabitat(0)
start = feedinghabitat.fhcr.seapodymFieldConstructor(
    './tmp_distribution_age_5_5.nc')


In [ ]:
print(current_u.coords)
print(current_v.coords)
print(habitat.coords)

Coordinates:
  * time     (time) datetime64[ns] 1979-01-15 1979-02-14 ... 2010-12-16
  * lat      (lat) float32 64.5 62.5 60.5 58.5 56.5 ... -47.5 -49.5 -51.5 -53.5
  * lon      (lon) float32 89.5 91.5 93.5 95.5 97.5 ... 283.5 285.5 287.5 289.5
Coordinates:
  * time     (time) datetime64[ns] 1979-01-15 1979-02-14 ... 2010-12-16
  * lat      (lat) float32 64.5 62.5 60.5 58.5 56.5 ... -47.5 -49.5 -51.5 -53.5
  * lon      (lon) float32 89.5 91.5 93.5 95.5 97.5 ... 283.5 285.5 287.5 289.5
Coordinates:
  * lon      (lon) float32 89.5 91.5 93.5 95.5 97.5 ... 283.5 285.5 287.5 289.5
  * lat      (lat) float32 64.5 62.5 60.5 58.5 56.5 ... -47.5 -49.5 -51.5 -53.5
  * time     (time) datetime64[ns] 1979-01-15 1979-02-14 ... 2010-12-16


<xarray.DataArray 'skj_cohort_density' (time: 1, lat: 60, lon: 101)>
array([[[nan, nan, ..., nan, nan],
        [nan, nan, ..., nan, nan],
        ...,
        [nan, nan, ..., nan, nan],
        [nan, nan, ..., nan, nan]]], dtype=float32)
Coordinates:
  * lon       (lon) float64 89.5 91.5 93.5 95.5 97.5 ... 283.5 285.5 287.5 289.5
  * lat       (lat) float64 -53.5 -51.5 -49.5 -47.5 ... 58.5 60.5 62.5 64.5
    mean_age  float64 ...
  * time      (time) datetime64[ns] 2008-01-15
Attributes:
    units:      Nb/sq.km
    long_name:  skipjack_cohort_21.83cm_density

In [ ]:
fieldsdatastructure.FieldsDataStructure(xml_filepath)

0.4893611123606695
0.4278765609783739
0.1601965094505096
0.9294158175770616


In [7]:
tmp = feedinghabitat.fhcr.seapodymFieldConstructor(
    './../data/SEAPODYM_data/run-test/skj_age5.dym',
    dym_varname='skj_age5')
tmp

<xarray.DataArray 'skj_age5' (time: 31, lat: 60, lon: 101)>
array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
...
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]], dtype=float32)
Coordinates:
  * time     (time) datetime64[ns] 2008-01-15 2008-02-15 ... 2010-07-17
  * lat      (lat) float32 64.5 62.5 60.5 58.5 56.5 ... -47.5 -49.5 -51.5 -53.5
  * lon      (lon) float32 89.5 91.5 93.5 95.5 97.5 ... 283.5 285.5 287.5 289.5

In [8]:
tmp.to_netcdf('./../data/SEAPODYM_data/run-test/skj_age5.nc')

In [10]:
from ikamoana import ParticleFile_Density_Functions

In [12]:
tmp = ParticleFile_Density_Functions.getPdata('./../data/SEAPODYM_data/run-test/skj_age5.nc')
tmp

{'time': array(['2008-01-15T00:00:00.000000000', '2008-02-15T00:00:00.000000000',
        '2008-03-16T00:00:00.000000000', '2008-04-16T00:00:00.000000000',
        '2008-05-16T00:00:00.000000000', '2008-06-16T00:00:00.000000000',
        '2008-07-16T00:00:00.000000000', '2008-08-16T00:00:00.000000000',
        '2008-09-15T00:00:00.000000000', '2008-10-16T00:00:00.000000000',
        '2008-11-15T00:00:00.000000000', '2008-12-16T00:00:00.000000000',
        '2009-01-15T00:00:00.000000000', '2009-02-14T00:00:00.000000000',
        '2009-03-17T00:00:00.000000000', '2009-04-16T00:00:00.000000000',
        '2009-05-17T00:00:00.000000000', '2009-06-16T00:00:00.000000000',
        '2009-07-17T00:00:00.000000000', '2009-08-16T00:00:00.000000000',
        '2009-09-15T00:00:00.000000000', '2009-10-16T00:00:00.000000000',
        '2009-11-15T00:00:00.000000000', '2009-12-16T00:00:00.000000000',
        '2010-01-15T00:00:00.000000000', '2010-02-14T00:00:00.000000000',
        '2010-03-17T00:00:00.0

In [13]:
ParticleFile_Density_Functions.calcDensity(tmp['lon'],tmp['lat'])

TypeError: object of type 'numpy.float32' has no len()

In [14]:
tmp['lon']

array([ 89.5,  91.5,  93.5,  95.5,  97.5,  99.5, 101.5, 103.5, 105.5,
       107.5, 109.5, 111.5, 113.5, 115.5, 117.5, 119.5, 121.5, 123.5,
       125.5, 127.5, 129.5, 131.5, 133.5, 135.5, 137.5, 139.5, 141.5,
       143.5, 145.5, 147.5, 149.5, 151.5, 153.5, 155.5, 157.5, 159.5,
       161.5, 163.5, 165.5, 167.5, 169.5, 171.5, 173.5, 175.5, 177.5,
       179.5, 181.5, 183.5, 185.5, 187.5, 189.5, 191.5, 193.5, 195.5,
       197.5, 199.5, 201.5, 203.5, 205.5, 207.5, 209.5, 211.5, 213.5,
       215.5, 217.5, 219.5, 221.5, 223.5, 225.5, 227.5, 229.5, 231.5,
       233.5, 235.5, 237.5, 239.5, 241.5, 243.5, 245.5, 247.5, 249.5,
       251.5, 253.5, 255.5, 257.5, 259.5, 261.5, 263.5, 265.5, 267.5,
       269.5, 271.5, 273.5, 275.5, 277.5, 279.5, 281.5, 283.5, 285.5,
       287.5, 289.5], dtype=float32)

In [5]:
try :
    float('')
except :
    print("coucou")

coucou


In [3]:
np.ravel(['coucou','alt'])

array(['coucou', 'alt'], dtype='<U6')

In [4]:
np.ravel('coucou')

array(['coucou'], dtype='<U6')

In [9]:
'alala' in np.ravel([1,'coucou',3])

False