In [1]:
import sys
sys.path.append('./../../')

In [2]:
import numpy as np
import ikamoana

In [3]:
fh = ikamoana.feedinghabitat.FeedingHabitat(
    xml_filepath="./../../data/feeding_habitat_data/po_2x30_historical_interim/skj_po_interim_2deg_configuration_file.xml")

In [4]:
# # Building climatic oxygen model
# for i in ["oxygen_L1", "oxygen_L2", "oxygen_L3"] :
#     data = fh.data_structure.variables_dictionary[i]
#     data = data.sel(time=data.time.data[0:12])
#     fh.data_structure.variables_dictionary[i] = data

# fh.data_structure.partial_oxygen_time_axis = True

In [5]:
fh.data_structure

# ------------------------------ #
# Summary of this data structure #
# ------------------------------ #

Root directory is :
	/home/ash/Documents/GitHub_Repositories/OFP-Ikamoana/Ikamoana/data/feeding_habitat_data/po_2x30_historical_interim/
Output directory is :
	/home/ash/Documents/GitHub_Repositories/OFP-Ikamoana/Ikamoana/data/feeding_habitat_data/po_2x30_historical_interim/output/
Time resolution is (in days) : 30
Space resolution is (in degrees) : 2.000000


# -------------------------------SPECIES----------------------------- #

The short name of the species is skj.
There is(are) 3	life stages considered in the model which are : ['larvae', 'juvenile', 'adult']
	- There is(are) 1	cohort(s) in life stage larvae.
	- There is(are) 2	cohort(s) in life stage juvenile.
	- There is(are) 34	cohort(s) in life stage adult.

Final age (in day) of each cohort is :
[  30.   60.   90.  120.  150.  180.  210.  240.  270.  300.  330.  360.
  390.  420.  450.  480.  510.  540.  570.  600.  630.  

### Find cohort by length or weight

In [6]:
_ = fh.data_structure.findCohortByLength(10, True)
_ = fh.data_structure.findCohortByWeight(10, True)

The cohort with the length closest to 10.000000 is cohort number 3 whose length is 11.650000
The cohort with the weight closest to 10.000000 is cohort number 27 whose weight is 9.810000


### A simple test

In [7]:
fh.computeEvolvingFeedingHabitat()

<xarray.DataArray 'Feeding_Habitat_Cohort_0_to_36' (time: 384, lat: 60, lon: 101)>
array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
...
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]], dtype=float32)
Coordinates:
  * time     (time) datetime64[ns] 1979-01-15T12:00:00 ... 2010-12-16T12:00:00
  * lat      (lat) float32 64.5 62.5 60.5 58.5 56.5 ... -47.5 -49.5 -51.5 -53.5
  * lon      (lon) float32 89.5 91.5 93.5 95.5 97.5 ... 283.5 285.5 287.5 289.5
    cohorts  (time) int64 0 1 2 3 4 5 6 7 8 9 ... 36 36 36 36 36 36 36 36 36 36
Attributes:
    description:   Feeding habitat of a species that evolves over time.
    cohort_start:  0
    cohort_end:    36
    time_start:    0
    time_end:      383
    lat_min:       None
    lat_max:       None
    lon_min:       None
    lon_max:       None
    eF_list:       [3.999907116416026, 0.05, 0.897307278945509, 0.0, 0.0, 3.9...
    sigma_0:       1.492626509052
    sigma_K:       3.00000257690523
    T_star_1:      31.09996321152416
    T_star_K:      26.04960048814059
    bT:            2.83057972721579
    gamma:         0.0001000000005808978
    o_star:        3.764163854561827
    deltaT:        30.0
    space_reso:    2.0

In [8]:
fh.computeEvolvingFeedingHabitat(0,10)

<xarray.DataArray 'Feeding_Habitat_Cohort_0_to_10' (time: 11, lat: 60, lon: 101)>
array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
...
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]], dtype=float32)
Coordinates:
  * time     (time) datetime64[ns] 1979-01-15T12:00:00 ... 1979-11-15T12:00:00
  * lat      (lat) float32 64.5 62.5 60.5 58.5 56.5 ... -47.5 -49.5 -51.5 -53.5
  * lon      (lon) float32 89.5 91.5 93.5 95.5 97.5 ... 283.5 285.5 287.5 289.5
    cohorts  (time) int64 0 1 2 3 4 5 6 7 8 9 10
Attributes:
    description:   Feeding habitat of a species that evolves over time.
    cohort_start:  0
    cohort_end:    10
    time_start:    0
    time_end:      10
    lat_min:       None
    lat_max:       None
    lon_min:       None
    lon_max:       None
    eF_list:       [3.999907116416026, 0.05, 0.897307278945509, 0.0, 0.0, 3.9...
    sigma_0:       1.492626509052
    sigma_K:       3.00000257690523
    T_star_1:      31.09996321152416
    T_star_K:      26.04960048814059
    bT:            2.83057972721579
    gamma:         0.0001000000005808978
    o_star:        3.764163854561827
    deltaT:        30.0
    space_reso:    2.0

### Test equals values

In [9]:
fh.computeEvolvingFeedingHabitat(
    cohort_start=0, cohort_end=10,
    time_start=10, time_end=None,
    lat_min=None, lat_max=20,
    lon_min=None, lon_max=None)

<xarray.DataArray 'Feeding_Habitat_Cohort_0_to_10' (time: 11, lat: 21, lon: 101)>
array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
...
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]], dtype=float32)
Coordinates:
  * time     (time) datetime64[ns] 1979-11-15T12:00:00 ... 1980-09-15T12:00:00
  * lat      (lat) float32 64.5 62.5 60.5 58.5 56.5 ... 32.5 30.5 28.5 26.5 24.5
  * lon      (lon) float32 89.5 91.5 93.5 95.5 97.5 ... 283.5 285.5 287.5 289.5
    cohorts  (time) int64 0 1 2 3 4 5 6 7 8 9 10
Attributes:
    description:   Feeding habitat of a species that evolves over time.
    cohort_start:  0
    cohort_end:    10
    time_start:    10
    time_end:      20
    lat_min:       None
    lat_max:       20
    lon_min:       None
    lon_max:       None
    eF_list:       [3.999907116416026, 0.05, 0.897307278945509, 0.0, 0.0, 3.9...
    sigma_0:       1.492626509052
    sigma_K:       3.00000257690523
    T_star_1:      31.09996321152416
    T_star_K:      26.04960048814059
    bT:            2.83057972721579
    gamma:         0.0001000000005808978
    o_star:        3.764163854561827
    deltaT:        30.0
    space_reso:    2.0

### Test aux bornes

In [10]:
fh.computeEvolvingFeedingHabitat(
    0,36,
    time_start=0, time_end=383,
    lat_min=0, lat_max=59,
    lon_min=0, lon_max=100,
    verbose=True)

<xarray.DataArray 'Feeding_Habitat_Cohort_0_to_36' (time: 384, lat: 60, lon: 101)>
array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
...
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]], dtype=float32)
Coordinates:
  * time     (time) datetime64[ns] 1979-01-15T12:00:00 ... 2010-12-16T12:00:00
  * lat      (lat) float32 64.5 62.5 60.5 58.5 56.5 ... -47.5 -49.5 -51.5 -53.5
  * lon      (lon) float32 89.5 91.5 93.5 95.5 97.5 ... 283.5 285.5 287.5 289.5
    cohorts  (time) int64 0 1 2 3 4 5 6 7 8 9 ... 36 36 36 36 36 36 36 36 36 36
Attributes:
    description:   Feeding habitat of a species that evolves over time.
    cohort_start:  0
    cohort_end:    36
    time_start:    0
    time_end:      383
    lat_min:       0
    lat_max:       59
    lon_min:       0
    lon_max:       100
    eF_list:       [3.999907116416026, 0.05, 0.897307278945509, 0.0, 0.0, 3.9...
    sigma_0:       1.492626509052
    sigma_K:       3.00000257690523
    T_star_1:      31.09996321152416
    T_star_K:      26.04960048814059
    bT:            2.83057972721579
    gamma:         0.0001000000005808978
    o_star:        3.764163854561827
    deltaT:        30.0
    space_reso:    2.0